# Generated by Django 5.1.4 on 2025-01-14 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serie', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='season',
            name='episode',
        ),
        migrations.AddField(
            model_name='season',
            name='director',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
