# Generated by Django 5.1.4 on 2025-01-17 00:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serie', '0002_remove_season_episode_season_director'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='episode',
            options={'ordering': ['season', 'episode_number'], 'verbose_name': 'Episode', 'verbose_name_plural': 'Episodes'},
        ),
        migrations.AlterModelOptions(
            name='season',
            options={'ordering': ['serie', 'season_number'], 'verbose_name': 'Season', 'verbose_name_plural': 'Seasons'},
        ),
        migrations.AlterField(
            model_name='episode',
            name='episode_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='serie',
            name='length',
            field=models.IntegerField(blank=True, help_text='Average episode length in minutes', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
