# Generated by Django 5.1.4 on 2025-01-20 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serie', '0003_alter_episode_options_alter_season_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serie',
            old_name='serie_poster',
            new_name='image_poster',
        ),
    ]
