# Generated by Django 5.1.4 on 2025-02-08 20:54

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serie', '0004_rename_serie_poster_serie_image_poster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='season',
            name='production',
        ),
        migrations.RemoveField(
            model_name='serie',
            name='country_of_origin',
        ),
        migrations.RemoveField(
            model_name='serie',
            name='length',
        ),
        migrations.RemoveField(
            model_name='serie',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='serie',
            name='release_date',
        ),
        migrations.AddField(
            model_name='episode',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='episode',
            name='length',
            field=models.IntegerField(blank=True, help_text='Average episode length in minutes', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='episode',
            name='tmdb_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='episode',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='season',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='season',
            name='image_poster',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='season',
            name='imdb_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='season',
            name='tmdb_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='season',
            name='trailers',
            field=models.JSONField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='season',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='serie',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serie',
            name='banner_poster',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serie',
            name='created_by',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serie',
            name='origin_country',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serie',
            name='original_language',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='serie',
            name='original_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='serie',
            name='production',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serie',
            name='spoken_languages',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serie',
            name='tagline',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serie',
            name='tmdb_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='serie',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='serie',
            name='vote_average',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serie',
            name='vote_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='episode_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
