# Generated by Django 5.1.4 on 2025-02-09 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serie', '0005_remove_season_production_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serie',
            old_name='ongoing',
            new_name='status',
        ),
        migrations.AlterField(
            model_name='serie',
            name='created_by',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
