# Generated by Django 5.1.4 on 2025-02-09 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serie', '0006_rename_ongoing_serie_status_alter_serie_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serie',
            name='status',
            field=models.CharField(blank=True, null=True),
        ),
    ]
