# Generated by Django 5.1.4 on 2025-02-09 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serie', '0007_alter_serie_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='guest_star',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='season',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
