# Generated by Django 5.1.4 on 2025-02-09 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serie', '0008_episode_guest_star_season_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='director',
            field=models.JSONField(blank=True, max_length=255, null=True),
        ),
    ]
