# Generated by Django 5.1.4 on 2025-02-09 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serie', '0009_alter_season_director'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='season',
            name='imdb_id',
        ),
        migrations.AddField(
            model_name='serie',
            name='imdb_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
