# Generated by Django 5.1.4 on 2025-02-09 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serie', '0010_remove_season_imdb_id_serie_imdb_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='banner_poster',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='season',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='season',
            name='image_poster',
            field=models.URLField(blank=True, null=True),
        ),
    ]
