# Generated by Django 5.1.4 on 2025-02-09 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serie', '0011_season_banner_poster_alter_season_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='season',
            name='banner_poster',
        ),
        migrations.AddField(
            model_name='episode',
            name='banner_poster',
            field=models.URLField(blank=True, null=True),
        ),
    ]
