# Generated by Django 5.1.4 on 2025-02-09 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serie', '0012_remove_season_banner_poster_episode_banner_poster'),
    ]

    operations = [
        migrations.RenameField(
            model_name='season',
            old_name='director',
            new_name='producer',
        ),
        migrations.RemoveField(
            model_name='season',
            name='writer',
        ),
        migrations.AddField(
            model_name='episode',
            name='director',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='episode',
            name='writer',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
