# Generated by Django 5.1.4 on 2025-02-09 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serie', '0013_rename_director_season_producer_remove_season_writer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='season_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
