# Generated by Django 5.1.4 on 2025-04-05 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serie', '0014_alter_season_season_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='serie',
            name='first_air_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serie',
            name='last_air_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
