# Generated by Django 5.1.4 on 2025-04-27 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serie', '0015_serie_first_air_date_serie_last_air_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='episode',
            old_name='added_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='season',
            old_name='added_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='serie',
            old_name='added_at',
            new_name='created_at',
        ),
    ]
