# Generated by Django 5.1.4 on 2025-08-22 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serie', '0017_episode_is_active_episode_slug_season_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serie',
            name='popularity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
