# Generated by Django 5.1.4 on 2025-08-31 19:31

from django.db import migrations

def forward(apps, schema_editor):
    Serie = apps.get_model("serie", "Serie")  # "movie" must match your app name
    Season = apps.get_model("serie", "Season")  # "movie" must match your app name
    Episode = apps.get_model("serie", "Episode")  # "movie" must match your app name

    # custom batch sizes
    BATCH_SERIE = 500
    BATCH_SEASON = 1000
    BATCH_EPISODE = 3000



    series_to_update = []
    updated = 0
    for serie in Serie.objects.iterator():
        posters = []
        banners = []

        if serie.image_poster:  # old single poster field
            posters.append(serie.image_poster)
        if serie.banner_poster:  # old single banner field
            banners.append(serie.banner_poster)

        if posters or banners:
            serie.poster_images = posters
            serie.banner_images = banners
            series_to_update.append(serie)
            updated += len(series_to_update)

        if len(series_to_update) >= BATCH_SERIE:
            Serie.objects.bulk_update(series_to_update, ["poster_images", "banner_images"])
            series_to_update.clear()

    if series_to_update:
        Serie.objects.bulk_update(series_to_update, ["poster_images", "banner_images"])
    print(f"Series updated: {updated}\n")


    season_to_update = []
    updated = 0
    for season in Season.objects.iterator():
        posters = []

        if season.image_poster:  # old single poster field
            posters.append(season.image_poster)

        if posters:
            season.poster_images = posters
            season_to_update.append(season)
            updated += len(season_to_update)

        if len(season_to_update) >= BATCH_SEASON:
            Season.objects.bulk_update(season_to_update, ["poster_images"])
            season_to_update.clear()

    if season_to_update:
        Season.objects.bulk_update(season_to_update, ["poster_images"])

    print(f"Seasons updated: {updated}\n")

    episode_to_update = []
    updated = 0
    for ep in Episode.objects.iterator():
        banners = []

        if ep.banner_poster:  # old single banner field
            banners.append(ep.banner_poster)

        if banners:
            ep.banner_images = banners
            episode_to_update.append(ep)
            updated += len(episode_to_update)

        if len(episode_to_update) >= BATCH_EPISODE:
            Episode.objects.bulk_update(episode_to_update, ["banner_images"])
            episode_to_update.clear()

    if season_to_update:
        Episode.objects.bulk_update(episode_to_update, ["banner_images"])

    print(f"Episodes updated: {updated}\n")


class Migration(migrations.Migration):

    dependencies = [
        ('serie', '0019_episode_banner_images_season_poster_images_and_more'),
    ]

    operations = [
        migrations.RunPython(forward),
    ]
