# Generated by Django 5.1.4 on 2025-08-31 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serie', '0020_auto_20250831_2131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='banner_poster',
        ),
        migrations.RemoveField(
            model_name='season',
            name='image_poster',
        ),
        migrations.RemoveField(
            model_name='serie',
            name='banner_poster',
        ),
        migrations.RemoveField(
            model_name='serie',
            name='image_poster',
        ),
    ]
