# Generated by Django 5.1.4 on 2025-09-21 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serie', '0021_remove_episode_banner_poster_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serie',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
