# Generated by Django 5.1.4 on 2025-11-06 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serie', '0022_alter_serie_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='episode_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='season',
            name='season_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='season',
            name='trailers',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
