# Generated by Django 5.1.4 on 2025-11-08 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serie', '0023_alter_episode_episode_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='episode',
            old_name='description',
            new_name='overview',
        ),
        migrations.RenameField(
            model_name='season',
            old_name='description',
            new_name='overview',
        ),
        migrations.RenameField(
            model_name='serie',
            old_name='description',
            new_name='overview',
        ),
    ]
