# Generated by Django 5.1.4 on 2025-11-09 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serie', '0024_rename_description_episode_overview_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='episode_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='season',
            name='season_number',
            field=models.IntegerField(),
        ),
    ]
