# Generated by Django 5.1.4 on 2025-11-11 19:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serie', '0025_alter_episode_episode_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serie',
            name='imdb_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='serie',
            name='vote_average',
            field=models.FloatField(blank=True, help_text='Select a value between 0 and 10.', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)]),
        ),
    ]
