# Generated by Django 5.1.4 on 2026-01-16 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serie', '0026_alter_serie_imdb_id_alter_serie_vote_average'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serie',
            options={'ordering': ['-id'], 'verbose_name': 'Serie', 'verbose_name_plural': 'Series'},
        ),
    ]
