# Generated by Django 5.1.4 on 2026-05-21 22:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# watchlist.migrations.0002_populate_from_user_library

class Migration(migrations.Migration):

    replaces = [('watchlist', '0001_initial'), ('watchlist', '0002_populate_from_user_library'), ('watchlist', '0003_alter_watchlist_media_alter_watchlist_user')]

    initial = True

    dependencies = [
        # ('media_library', '0002_migrate_movie_serie_to_media'),
        ('media_library', '0001_squashed_0002_migrate_movie_serie_to_media'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('personal_note', models.TextField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(blank=True, choices=[('to watch', 'Plan to Watch'), ('watching', 'Currently Watching'), ('finished', 'Finished Watching'), ('dropped', 'Dropped out')], default=None, max_length=128, null=True)),
                ('media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watchlisted_by', to='media_library.media')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Watchlist',
                'verbose_name_plural': 'Watchlists',
                'db_table': 'watchlist',
                'ordering': ['-id'],
                'unique_together': {('user', 'media')},
            },
        ),
        # migrations.RunPython(
        #     code=watchlist.migrations.0002_populate_from_user_library.forwards,
        #     reverse_code=watchlist.migrations.0002_populate_from_user_library.backwards,
        # ),
        migrations.RunPython(
            migrations.RunPython.noop,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='media',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlisted_by', to='media_library.media'),
        ),
        # migrations.AlterField(
        #     model_name='watchlist',
        #     name='user',
        #     field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to=settings.AUTH_USER_MODEL),
        # ),
    ]
