# Generated by Django 5.1.4 on 2026-04-30 00:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media_library', '0002_migrate_movie_serie_to_media'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('personal_note', models.TextField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(blank=True, choices=[('to watch', 'Plan to Watch'), ('watching', 'Currently Watching'), ('finished', 'Finished Watching'), ('dropped', 'Dropped out')], default=None, max_length=128, null=True)),
                ('media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watchlisted_by', to='media_library.media')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_watchlist', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Watchlist',
                'verbose_name_plural': 'Watchlists',
                'db_table': 'watchlist',
                'ordering': ['-id'],
                'unique_together': {('user', 'media')},
            },
        ),
    ]
