# Generated by Django 5.1.4 on 2026-04-30 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0001_initial'),
    ]

    operations = [
    ]
