# Generated by Django 5.1.4 on 2026-04-30 00:05


from django.db import migrations, transaction

# CHUNK_SIZE = 500

def forwards(apps, schema_editor):
    pass
    # old_watchlist_mod = apps.get_model("user_library", "WatchList")
    # new_watchlist_mod = apps.get_model("watchlist", "Watchlist")
    # transfer_map = apps.get_model("media_library", "MediaTransferMap")

    # # Build lookup dicts to fetch the right new Pk on the Media model
    # movie_map = dict(
    #     transfer_map.objects.filter(media_type="movie").values_list(
    #         "old_pk", "new_media_pk"
    #     )
    # )
    # serie_map = dict(
    #     transfer_map.objects.filter(media_type="serie").values_list(
    #         "old_pk", "new_media_pk"
    #     )
    # )

    # skipped = 0

    # with transaction.atomic():
    #     for old in old_watchlist_mod.objects.order_by('id').iterator(chunk_size=CHUNK_SIZE):
    #         if old.movie_id:
    #             new_media_pk = movie_map.get(old.movie_id)
    #         elif old.serie_id:
    #             new_media_pk = serie_map.get(old.serie_id)
    #         else:
    #             skipped += 1
    #             continue

    #         if not new_media_pk:
    #             print(f"WARNING: no media mapping for watchlist pk={old.pk}")
    #             skipped += 1
    #             continue

    #         new_entry = new_watchlist_mod.objects.create(
    #             user_id=old.user_id,
    #             media_id=new_media_pk,
    #             personal_note=old.personal_note,
    #             status=old.status,
    #         )

    #         old_watchlist_mod.objects.filter(pk=new_entry.pk).update(
    #             created_at=old.created_at,
    #             updated_at=old.updated_at,
    #         )

    # print(f"Watchlist migrated. Skipped: {skipped}")


def backwards(apps, schema_editor):
    apps.get_model("watchlist", "Watchlist").objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0001_initial'),
        # ("media_library", "0002_migrate_movie_serie_to_media"),
        ("media_library", "0001_squashed_0002_migrate_movie_serie_to_media"),
        # ("user_library", "0020_alter_watchedcontent_rewatch_alter_watchlist_status"),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
