--
-- PostgreSQL database dump
--

-- Dumped from database version 17.2
-- Dumped by pg_dump version 17.2

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: movie_admin
--

-- *not* creating schema, since initdb creates it


ALTER SCHEMA public OWNER TO movie_admin;

--
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: movie_admin
--

COMMENT ON SCHEMA public IS '';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: movie_admin
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO movie_admin;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: movie_admin
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: movie_admin
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO movie_admin;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: movie_admin
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: movie_admin
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO movie_admin;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: movie_admin
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: movie_admin
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO movie_admin;

--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: movie_admin
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.auth_user_groups OWNER TO movie_admin;

--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: movie_admin
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: movie_admin
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: movie_admin
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_user_user_permissions OWNER TO movie_admin;

--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: movie_admin
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: movie_admin
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO movie_admin;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: movie_admin
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: movie_admin
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO movie_admin;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: movie_admin
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: movie_admin
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO movie_admin;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: movie_admin
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: movie_admin
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO movie_admin;

--
-- Name: episode; Type: TABLE; Schema: public; Owner: movie_admin
--

CREATE TABLE public.episode (
    id bigint NOT NULL,
    episode_number smallint,
    title character varying(255) NOT NULL,
    description text,
    release_date date,
    season_id bigint NOT NULL,
    CONSTRAINT episode_episode_number_check CHECK ((episode_number >= 0))
);


ALTER TABLE public.episode OWNER TO movie_admin;

--
-- Name: episode_id_seq; Type: SEQUENCE; Schema: public; Owner: movie_admin
--

ALTER TABLE public.episode ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.episode_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: movie; Type: TABLE; Schema: public; Owner: movie_admin
--

CREATE TABLE public.movie (
    id bigint NOT NULL,
    title character varying(255) NOT NULL,
    release_date date,
    country_of_origin character varying(255),
    production character varying(255),
    writer jsonb,
    casting jsonb,
    rating integer,
    length integer,
    description text,
    genre jsonb,
    film_poster character varying(200),
    added_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


ALTER TABLE public.movie OWNER TO movie_admin;

--
-- Name: movie_id_seq; Type: SEQUENCE; Schema: public; Owner: movie_admin
--

ALTER TABLE public.movie ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.movie_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: season; Type: TABLE; Schema: public; Owner: movie_admin
--

CREATE TABLE public.season (
    id bigint NOT NULL,
    season_number smallint,
    episode smallint,
    production character varying(255),
    casting jsonb,
    writer jsonb,
    description text,
    serie_id bigint NOT NULL,
    CONSTRAINT season_episode_check CHECK ((episode >= 0)),
    CONSTRAINT season_season_number_check CHECK ((season_number >= 0))
);


ALTER TABLE public.season OWNER TO movie_admin;

--
-- Name: season_id_seq; Type: SEQUENCE; Schema: public; Owner: movie_admin
--

ALTER TABLE public.season ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.season_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: serie; Type: TABLE; Schema: public; Owner: movie_admin
--

CREATE TABLE public.serie (
    id bigint NOT NULL,
    title character varying(255) NOT NULL,
    release_date date,
    country_of_origin character varying(255),
    rating integer,
    description text,
    genre jsonb,
    ongoing boolean,
    serie_poster character varying(200),
    length integer
);


ALTER TABLE public.serie OWNER TO movie_admin;

--
-- Name: serie_id_seq; Type: SEQUENCE; Schema: public; Owner: movie_admin
--

ALTER TABLE public.serie ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.serie_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_library_likedmovie; Type: TABLE; Schema: public; Owner: movie_admin
--

CREATE TABLE public.user_library_likedmovie (
    id bigint NOT NULL,
    liked_at timestamp with time zone NOT NULL,
    movie_id bigint NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.user_library_likedmovie OWNER TO movie_admin;

--
-- Name: user_library_likedmovie_id_seq; Type: SEQUENCE; Schema: public; Owner: movie_admin
--

ALTER TABLE public.user_library_likedmovie ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_library_likedmovie_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_library_likedserie; Type: TABLE; Schema: public; Owner: movie_admin
--

CREATE TABLE public.user_library_likedserie (
    id bigint NOT NULL,
    liked_at timestamp with time zone NOT NULL,
    serie_id bigint NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.user_library_likedserie OWNER TO movie_admin;

--
-- Name: user_library_likedserie_id_seq; Type: SEQUENCE; Schema: public; Owner: movie_admin
--

ALTER TABLE public.user_library_likedserie ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_library_likedserie_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_library_watchedmovie; Type: TABLE; Schema: public; Owner: movie_admin
--

CREATE TABLE public.user_library_watchedmovie (
    id bigint NOT NULL,
    rating integer,
    rewatch character varying,
    watched_at timestamp with time zone NOT NULL,
    personal_note text,
    movie_id bigint NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.user_library_watchedmovie OWNER TO movie_admin;

--
-- Name: user_library_watchedmovie_id_seq; Type: SEQUENCE; Schema: public; Owner: movie_admin
--

ALTER TABLE public.user_library_watchedmovie ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_library_watchedmovie_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_library_watchlist; Type: TABLE; Schema: public; Owner: movie_admin
--

CREATE TABLE public.user_library_watchlist (
    id bigint NOT NULL,
    added_at timestamp with time zone NOT NULL,
    personal_note text,
    status character varying,
    movie_id bigint NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.user_library_watchlist OWNER TO movie_admin;

--
-- Name: user_library_watchlist_id_seq; Type: SEQUENCE; Schema: public; Owner: movie_admin
--

ALTER TABLE public.user_library_watchlist ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_library_watchlist_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_profile; Type: TABLE; Schema: public; Owner: movie_admin
--

CREATE TABLE public.user_profile (
    id bigint NOT NULL,
    date_of_birth date,
    phone character varying(15),
    country character varying(100),
    city character varying(100),
    profile_picture character varying(100) NOT NULL,
    bio text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.user_profile OWNER TO movie_admin;

--
-- Name: user_profile_id_seq; Type: SEQUENCE; Schema: public; Owner: movie_admin
--

ALTER TABLE public.user_profile ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_profile_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: movie_admin
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: movie_admin
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: movie_admin
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: movie_admin
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: movie_admin
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: movie_admin
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: movie_admin
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: movie_admin
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: movie_admin
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: movie_admin
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: movie_admin
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: movie_admin
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: movie_admin
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: movie_admin
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: movie_admin
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: movie_admin
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: movie_admin
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: episode episode_pkey; Type: CONSTRAINT; Schema: public; Owner: movie_admin
--

ALTER TABLE ONLY public.episode
    ADD CONSTRAINT episode_pkey PRIMARY KEY (id);


--
-- Name: episode episode_season_id_episode_number_0ee15962_uniq; Type: CONSTRAINT; Schema: public; Owner: movie_admin
--

ALTER TABLE ONLY public.episode
    ADD CONSTRAINT episode_season_id_episode_number_0ee15962_uniq UNIQUE (season_id, episode_number);


--
-- Name: movie movie_pkey; Type: CONSTRAINT; Schema: public; Owner: movie_admin
--

ALTER TABLE ONLY public.movie
    ADD CONSTRAINT movie_pkey PRIMARY KEY (id);


--
-- Name: season season_pkey; Type: CONSTRAINT; Schema: public; Owner: movie_admin
--

ALTER TABLE ONLY public.season
    ADD CONSTRAINT season_pkey PRIMARY KEY (id);


--
-- Name: season season_serie_id_season_number_927aea58_uniq; Type: CONSTRAINT; Schema: public; Owner: movie_admin
--

ALTER TABLE ONLY public.season
    ADD CONSTRAINT season_serie_id_season_number_927aea58_uniq UNIQUE (serie_id, season_number);


--
-- Name: serie serie_pkey; Type: CONSTRAINT; Schema: public; Owner: movie_admin
--

ALTER TABLE ONLY public.serie
    ADD CONSTRAINT serie_pkey PRIMARY KEY (id);


--
-- Name: user_library_likedmovie user_library_likedmovie_pkey; Type: CONSTRAINT; Schema: public; Owner: movie_admin
--

ALTER TABLE ONLY public.user_library_likedmovie
    ADD CONSTRAINT user_library_likedmovie_pkey PRIMARY KEY (id);


--
-- Name: user_library_likedmovie user_library_likedmovie_user_id_movie_id_c0591b78_uniq; Type: CONSTRAINT; Schema: public; Owner: movie_admin
--

ALTER TABLE ONLY public.user_library_likedmovie
    ADD CONSTRAINT user_library_likedmovie_user_id_movie_id_c0591b78_uniq UNIQUE (user_id, movie_id);


--
-- Name: user_library_likedserie user_library_likedserie_pkey; Type: CONSTRAINT; Schema: public; Owner: movie_admin
--

ALTER TABLE ONLY public.user_library_likedserie
    ADD CONSTRAINT user_library_likedserie_pkey PRIMARY KEY (id);


--
-- Name: user_library_likedserie user_library_likedserie_user_id_serie_id_523a71be_uniq; Type: CONSTRAINT; Schema: public; Owner: movie_admin
--

ALTER TABLE ONLY public.user_library_likedserie
    ADD CONSTRAINT user_library_likedserie_user_id_serie_id_523a71be_uniq UNIQUE (user_id, serie_id);


--
-- Name: user_library_watchedmovie user_library_watchedmovie_pkey; Type: CONSTRAINT; Schema: public; Owner: movie_admin
--

ALTER TABLE ONLY public.user_library_watchedmovie
    ADD CONSTRAINT user_library_watchedmovie_pkey PRIMARY KEY (id);


--
-- Name: user_library_watchlist user_library_watchlist_pkey; Type: CONSTRAINT; Schema: public; Owner: movie_admin
--

ALTER TABLE ONLY public.user_library_watchlist
    ADD CONSTRAINT user_library_watchlist_pkey PRIMARY KEY (id);


--
-- Name: user_library_watchlist user_library_watchlist_user_id_movie_id_5e0adfd9_uniq; Type: CONSTRAINT; Schema: public; Owner: movie_admin
--

ALTER TABLE ONLY public.user_library_watchlist
    ADD CONSTRAINT user_library_watchlist_user_id_movie_id_5e0adfd9_uniq UNIQUE (user_id, movie_id);


--
-- Name: user_profile user_profile_pkey; Type: CONSTRAINT; Schema: public; Owner: movie_admin
--

ALTER TABLE ONLY public.user_profile
    ADD CONSTRAINT user_profile_pkey PRIMARY KEY (id);


--
-- Name: user_profile user_profile_user_id_key; Type: CONSTRAINT; Schema: public; Owner: movie_admin
--

ALTER TABLE ONLY public.user_profile
    ADD CONSTRAINT user_profile_user_id_key UNIQUE (user_id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: movie_admin
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: movie_admin
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: movie_admin
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: movie_admin
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: movie_admin
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: movie_admin
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: movie_admin
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: movie_admin
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: movie_admin
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: movie_admin
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: movie_admin
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: movie_admin
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: movie_admin
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: episode_season_id_f9fa2dd2; Type: INDEX; Schema: public; Owner: movie_admin
--

CREATE INDEX episode_season_id_f9fa2dd2 ON public.episode USING btree (season_id);


--
-- Name: season_serie_id_127821d4; Type: INDEX; Schema: public; Owner: movie_admin
--

CREATE INDEX season_serie_id_127821d4 ON public.season USING btree (serie_id);


--
-- Name: user_library_likedmovie_movie_id_ded85333; Type: INDEX; Schema: public; Owner: movie_admin
--

CREATE INDEX user_library_likedmovie_movie_id_ded85333 ON public.user_library_likedmovie USING btree (movie_id);


--
-- Name: user_library_likedmovie_user_id_9475c138; Type: INDEX; Schema: public; Owner: movie_admin
--

CREATE INDEX user_library_likedmovie_user_id_9475c138 ON public.user_library_likedmovie USING btree (user_id);


--
-- Name: user_library_likedserie_serie_id_848651af; Type: INDEX; Schema: public; Owner: movie_admin
--

CREATE INDEX user_library_likedserie_serie_id_848651af ON public.user_library_likedserie USING btree (serie_id);


--
-- Name: user_library_likedserie_user_id_8de2a12f; Type: INDEX; Schema: public; Owner: movie_admin
--

CREATE INDEX user_library_likedserie_user_id_8de2a12f ON public.user_library_likedserie USING btree (user_id);


--
-- Name: user_library_watchedmovie_movie_id_bce1985d; Type: INDEX; Schema: public; Owner: movie_admin
--

CREATE INDEX user_library_watchedmovie_movie_id_bce1985d ON public.user_library_watchedmovie USING btree (movie_id);


--
-- Name: user_library_watchedmovie_user_id_02c37555; Type: INDEX; Schema: public; Owner: movie_admin
--

CREATE INDEX user_library_watchedmovie_user_id_02c37555 ON public.user_library_watchedmovie USING btree (user_id);


--
-- Name: user_library_watchlist_movie_id_bab7462b; Type: INDEX; Schema: public; Owner: movie_admin
--

CREATE INDEX user_library_watchlist_movie_id_bab7462b ON public.user_library_watchlist USING btree (movie_id);


--
-- Name: user_library_watchlist_user_id_a8d64ce8; Type: INDEX; Schema: public; Owner: movie_admin
--

CREATE INDEX user_library_watchlist_user_id_a8d64ce8 ON public.user_library_watchlist USING btree (user_id);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: movie_admin
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: movie_admin
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: movie_admin
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: movie_admin
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: movie_admin
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: movie_admin
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: movie_admin
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: movie_admin
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: movie_admin
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: episode episode_season_id_f9fa2dd2_fk_season_id; Type: FK CONSTRAINT; Schema: public; Owner: movie_admin
--

ALTER TABLE ONLY public.episode
    ADD CONSTRAINT episode_season_id_f9fa2dd2_fk_season_id FOREIGN KEY (season_id) REFERENCES public.season(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: season season_serie_id_127821d4_fk_serie_id; Type: FK CONSTRAINT; Schema: public; Owner: movie_admin
--

ALTER TABLE ONLY public.season
    ADD CONSTRAINT season_serie_id_127821d4_fk_serie_id FOREIGN KEY (serie_id) REFERENCES public.serie(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: user_library_likedmovie user_library_likedmovie_movie_id_ded85333_fk_movie_id; Type: FK CONSTRAINT; Schema: public; Owner: movie_admin
--

ALTER TABLE ONLY public.user_library_likedmovie
    ADD CONSTRAINT user_library_likedmovie_movie_id_ded85333_fk_movie_id FOREIGN KEY (movie_id) REFERENCES public.movie(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: user_library_likedmovie user_library_likedmovie_user_id_9475c138_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: movie_admin
--

ALTER TABLE ONLY public.user_library_likedmovie
    ADD CONSTRAINT user_library_likedmovie_user_id_9475c138_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: user_library_likedserie user_library_likedserie_serie_id_848651af_fk_serie_id; Type: FK CONSTRAINT; Schema: public; Owner: movie_admin
--

ALTER TABLE ONLY public.user_library_likedserie
    ADD CONSTRAINT user_library_likedserie_serie_id_848651af_fk_serie_id FOREIGN KEY (serie_id) REFERENCES public.serie(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: user_library_likedserie user_library_likedserie_user_id_8de2a12f_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: movie_admin
--

ALTER TABLE ONLY public.user_library_likedserie
    ADD CONSTRAINT user_library_likedserie_user_id_8de2a12f_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: user_library_watchedmovie user_library_watchedmovie_movie_id_bce1985d_fk_movie_id; Type: FK CONSTRAINT; Schema: public; Owner: movie_admin
--

ALTER TABLE ONLY public.user_library_watchedmovie
    ADD CONSTRAINT user_library_watchedmovie_movie_id_bce1985d_fk_movie_id FOREIGN KEY (movie_id) REFERENCES public.movie(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: user_library_watchedmovie user_library_watchedmovie_user_id_02c37555_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: movie_admin
--

ALTER TABLE ONLY public.user_library_watchedmovie
    ADD CONSTRAINT user_library_watchedmovie_user_id_02c37555_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: user_library_watchlist user_library_watchlist_movie_id_bab7462b_fk_movie_id; Type: FK CONSTRAINT; Schema: public; Owner: movie_admin
--

ALTER TABLE ONLY public.user_library_watchlist
    ADD CONSTRAINT user_library_watchlist_movie_id_bab7462b_fk_movie_id FOREIGN KEY (movie_id) REFERENCES public.movie(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: user_library_watchlist user_library_watchlist_user_id_a8d64ce8_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: movie_admin
--

ALTER TABLE ONLY public.user_library_watchlist
    ADD CONSTRAINT user_library_watchlist_user_id_a8d64ce8_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: user_profile user_profile_user_id_8fdce8e2_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: movie_admin
--

ALTER TABLE ONLY public.user_profile
    ADD CONSTRAINT user_profile_user_id_8fdce8e2_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: movie_admin
--

REVOKE USAGE ON SCHEMA public FROM PUBLIC;
GRANT ALL ON SCHEMA public TO PUBLIC;


--
-- PostgreSQL database dump complete
--

