# Generated by Django 5.1.4 on 2025-01-06 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_library', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='status',
            field=models.CharField(blank=True, choices=[('plan', 'Plan to Watch'), ('watching', 'Currently Watching'), ('finished', 'Finished Watching'), ('dropped', 'Dropped')], null=True),
        ),
    ]
