# Generated by Django 5.1.4 on 2025-01-14 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_library', '0002_alter_watchlist_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='likedmovie',
            options={'verbose_name': 'liked_movie', 'verbose_name_plural': 'liked_movies'},
        ),
        migrations.AlterModelOptions(
            name='likedserie',
            options={'verbose_name': 'liked_serie', 'verbose_name_plural': 'liked_series'},
        ),
        migrations.AlterModelOptions(
            name='watchedmovie',
            options={'verbose_name': 'watched_movie', 'verbose_name_plural': 'watched_movies'},
        ),
        migrations.AlterModelOptions(
            name='watchlist',
            options={'verbose_name': 'Watch_List', 'verbose_name_plural': 'Watch_Lists'},
        ),
        migrations.AlterField(
            model_name='watchedmovie',
            name='rewatch',
            field=models.CharField(blank=True, choices=[('never', 'Never again.'), ('no', 'Once was enough.'), ('maybe', 'Maybe in some years.'), ('worth', "It's Worth a rewatch."), ('totally', 'Must rewatch it!')], null=True),
        ),
        migrations.AlterModelTable(
            name='likedmovie',
            table='liked_movies',
        ),
        migrations.AlterModelTable(
            name='likedserie',
            table='liked_series',
        ),
        migrations.AlterModelTable(
            name='watchedmovie',
            table='watched_movies',
        ),
        migrations.AlterModelTable(
            name='watchlist',
            table='watch_list',
        ),
    ]
