# Generated by Django 5.1.4 on 2025-01-17 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_library', '0004_like'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='like',
            table='user_Like',
        ),
    ]
