# Generated by Django 5.1.4 on 2025-01-18 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_library', '0005_alter_like_table'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='likedserie',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='likedserie',
            name='serie',
        ),
        migrations.RemoveField(
            model_name='likedserie',
            name='user',
        ),
        migrations.DeleteModel(
            name='LikedMovie',
        ),
        migrations.DeleteModel(
            name='LikedSerie',
        ),
    ]
