# Generated by Django 5.1.4 on 2025-02-03 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_library', '0007_alter_watchlist_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='like',
            options={'ordering': ['-liked_on'], 'verbose_name': 'Like', 'verbose_name_plural': 'Likes'},
        ),
        migrations.AlterModelOptions(
            name='watchedcontent',
            options={'ordering': ['-watched_on'], 'verbose_name': 'watched_content', 'verbose_name_plural': 'watched_contents'},
        ),
        migrations.AlterModelOptions(
            name='watchlist',
            options={'ordering': ['-added_on'], 'verbose_name': 'Watch_List', 'verbose_name_plural': 'Watch_Lists'},
        ),
        migrations.RenameField(
            model_name='like',
            old_name='liked_at',
            new_name='liked_on',
        ),
        migrations.RenameField(
            model_name='watchedcontent',
            old_name='watched_at',
            new_name='watched_on',
        ),
        migrations.RenameField(
            model_name='watchlist',
            old_name='added_at',
            new_name='added_on',
        ),
        migrations.AlterField(
            model_name='watchedcontent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watched_content', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='content_type',
            field=models.CharField(choices=[('movie', 'Movie'), ('serie', 'Serie')], default='movie', max_length=25),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='watchedcontent',
            unique_together={('user', 'content_type', 'object_id')},
        ),
        migrations.AlterUniqueTogether(
            name='watchlist',
            unique_together={('user', 'content_type', 'object_id')},
        ),
        migrations.AlterModelTable(
            name='like',
            table='Like',
        ),
    ]
