# Generated by Django 5.1.4 on 2025-04-11 03:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_library', '0009_alter_like_options_alter_like_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='watchlist',
            options={'ordering': ['-created_on'], 'verbose_name': 'Watch_List', 'verbose_name_plural': 'Watch_Lists'},
        ),
        migrations.RenameField(
            model_name='watchlist',
            old_name='added_on',
            new_name='created_on',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='updated_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
