# Generated by Django 5.1.4 on 2025-04-27 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_library', '0010_alter_watchlist_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='like',
            options={'verbose_name': 'like', 'verbose_name_plural': 'likes'},
        ),
        migrations.AlterModelOptions(
            name='watchedcontent',
            options={'verbose_name': 'watched_content', 'verbose_name_plural': 'watched_contents'},
        ),
        migrations.AlterModelOptions(
            name='watchlist',
            options={'verbose_name': 'Watch_List', 'verbose_name_plural': 'Watch_Lists'},
        ),
        migrations.RenameField(
            model_name='like',
            old_name='liked_on',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='watchlist',
            old_name='created_on',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='watchedcontent',
            name='watched_on',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='updated_on',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
