# Generated by Django 5.1.4 on 2025-04-28 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_library', '0012_like_is_active_like_slug_like_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='like',
            options={'ordering': ['-created_at'], 'verbose_name': 'like', 'verbose_name_plural': 'likes'},
        ),
        migrations.AlterModelOptions(
            name='watchlist',
            options={'ordering': ['-created_at'], 'verbose_name': 'Watch_List', 'verbose_name_plural': 'Watch_Lists'},
        ),
    ]
