# Generated by Django 5.1.4 on 2025-04-28 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_library', '0013_alter_like_options_alter_watchlist_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='watchedcontent',
            options={'ordering': ['-created_at'], 'verbose_name': 'watched_content', 'verbose_name_plural': 'watched_contents'},
        ),
    ]
