# Generated by Django 5.1.4 on 2025-08-16 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0016_movie_is_active_movie_slug'),
        ('serie', '0017_episode_is_active_episode_slug_season_is_active_and_more'),
        ('user_library', '0014_alter_watchedcontent_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watch_list', to='movie.movie'),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='serie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watch_list', to='serie.serie'),
        ),
    ]
