# Generated by Django 5.1.4 on 2025-08-17 21:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0016_movie_is_active_movie_slug'),
        ('serie', '0017_episode_is_active_episode_slug_season_is_active_and_more'),
        ('user_library', '0015_watchlist_movie_watchlist_serie'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='watchlist',
            options={'ordering': ['-id'], 'verbose_name': 'Watch_List', 'verbose_name_plural': 'Watch_Lists'},
        ),
        migrations.AlterUniqueTogether(
            name='watchlist',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='watchlist',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('movie__isnull', False), ('serie__isnull', True)), models.Q(('movie__isnull', True), ('serie__isnull', False)), _connector='OR'), name='only_one_content_type'),
        ),
        migrations.AddConstraint(
            model_name='watchlist',
            constraint=models.UniqueConstraint(condition=models.Q(('movie__isnull', False)), fields=('user', 'movie'), name='unique_movie_watchlist'),
        ),
        migrations.AddConstraint(
            model_name='watchlist',
            constraint=models.UniqueConstraint(condition=models.Q(('serie__isnull', False)), fields=('user', 'serie'), name='unique_serie_watchlist'),
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='object_id',
        ),
    ]
