# Generated by Django 5.1.4 on 2025-09-21 21:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0020_movie_status'),
        ('serie', '0022_alter_serie_status'),
        ('user_library', '0017_alter_watchlist_movie_alter_watchlist_serie_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='status',
            field=models.CharField(blank=True, choices=[('plan', 'Plan to Watch'), ('watching', 'Currently Watching'), ('finished', 'Finished Watching'), ('dropped', 'Dropped out')], null=True),
        ),
        migrations.AlterUniqueTogether(
            name='watchlist',
            unique_together={('user', 'movie', 'serie')},
        ),
    ]
