# Generated by Django 5.1.4 on 2025-11-16 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_library', '0018_alter_watchlist_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='status',
            field=models.CharField(blank=True, choices=[('to watch', 'Plan to Watch'), ('watching', 'Currently Watching'), ('finished', 'Finished Watching'), ('dropped', 'Dropped out')], default=None, null=True),
        ),
    ]
