# Generated by Django 5.1.4 on 2025-12-05 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_library', '0019_alter_watchlist_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchedcontent',
            name='rewatch',
            field=models.CharField(blank=True, choices=[('never', 'Never again.'), ('no', 'Once was enough.'), ('maybe', 'Maybe in some years.'), ('worth', "It's Worth a rewatch."), ('totally', 'Must rewatch it!')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='status',
            field=models.CharField(blank=True, choices=[('to watch', 'Plan to Watch'), ('watching', 'Currently Watching'), ('finished', 'Finished Watching'), ('dropped', 'Dropped out')], default=None, max_length=128, null=True),
        ),
    ]
