# Generated by Django 5.1.4 on 2026-05-22 00:31

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('review', '0001_initial'), ('review', '0002_alter_review_rewatch')]

    initial = True

    dependencies = [
        # ('media_library', '0002_migrate_movie_serie_to_media'),
        ('media_library', '0001_squashed_0002_migrate_movie_serie_to_media'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('status', models.CharField(choices=[('watching', 'Watching'), ('completed', 'Completed'), ('dropped', 'Dropped'), ('paused', 'Paused')], default='completed', max_length=20)),
                ('review', models.TextField(blank=True, max_length=2000, null=True)),
                ('rewatch', models.CharField(blank=True, choices=[('no', 'No.'), ('maybe', 'Maybe.'), ('yes', 'Yes, worth it.')], max_length=20, null=True)),
                ('score', models.FloatField(blank=True, help_text='Score between 0.0 and 10.0', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='media_library.media')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'db_table': 'review',
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'media'), name='unique_user_media_watched')],
            },
        ),
    ]
