# Generated by Django 5.1.4 on 2026-05-20 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rewatch',
            field=models.CharField(blank=True, choices=[('no', 'No.'), ('maybe', 'Maybe.'), ('yes', 'Yes, worth it.')], max_length=20, null=True),
        ),
    ]
