# Generated by Django 5.1.4 on 2025-01-03 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('country_of_origin', models.CharField(blank=True, max_length=255, null=True)),
                ('production', models.CharField(blank=True, max_length=255, null=True)),
                ('writer', models.JSONField(blank=True, null=True)),
                ('casting', models.JSONField(blank=True, null=True)),
                ('rating', models.IntegerField(blank=True, choices=[(1, '1 - Terrible'), (2, '2 - Very Bad'), (3, '3 - Bad'), (4, '4 - Poor'), (5, '5 - Average'), (6, '6 - Fair'), (7, '7 - Good'), (8, '8 - Very Good'), (9, '9 - Excellent'), (10, '10 - Masterpiece')], null=True)),
                ('length', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('genre', models.JSONField(blank=True, null=True)),
                ('film_poster', models.URLField(blank=True, null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Movie',
                'verbose_name_plural': 'Movies',
                'db_table': 'movie',
            },
        ),
    ]
