# Generated by Django 5.1.4 on 2025-02-03 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_remove_movie_rating_movie_banner_poster_movie_budget_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
