# Generated by Django 5.1.4 on 2025-02-03 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_alter_movie_director'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='original_language',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
