# Generated by Django 5.1.4 on 2025-02-03 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_movie_original_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='country_of_origin',
            new_name='origin_country',
        ),
    ]
