# Generated by Django 5.1.4 on 2025-02-03 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_rename_country_of_origin_movie_origin_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='origin_country',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
