# Generated by Django 5.1.4 on 2025-02-04 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0008_alter_movie_origin_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='trailer_youtube_id',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
