# Generated by Django 5.1.4 on 2025-02-06 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0009_movie_trailer_youtube_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='trailer_youtube_id',
            field=models.JSONField(blank=True, max_length=11, null=True),
        ),
    ]
