# Generated by Django 5.1.4 on 2025-02-06 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0010_alter_movie_trailer_youtube_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='trailer_youtube_id',
            new_name='trailers',
        ),
    ]
