# Generated by Django 5.1.4 on 2025-02-24 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0013_alter_movie_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['id'], 'verbose_name': 'Movie', 'verbose_name_plural': 'Movies'},
        ),
    ]
