# Generated by Django 5.1.4 on 2025-04-27 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0014_alter_movie_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='added_at',
            new_name='created_at',
        ),
    ]
