# Generated by Django 5.1.4 on 2025-04-27 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0015_rename_added_at_movie_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
