# Generated by Django 5.1.4 on 2025-08-31 13:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0016_movie_is_active_movie_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='banner_images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='movie',
            name='poster_images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None),
        ),
    ]
