# Generated by Django 5.1.4 on 2025-08-31 14:08

from django.db import migrations

def forward(apps, schema_editor):
    Movie = apps.get_model("movie", "Movie")  # "movie" must match your app name
    updated = 0

    for movie in Movie.objects.all():
        posters = []
        banners = []

        if movie.image_poster:  # old single poster field
            posters.append(movie.image_poster)
        if movie.banner_poster:  # old single banner field
            banners.append(movie.banner_poster)

        if posters or banners:
            movie.poster_images = posters
            movie.banner_images = banners
            movie.save(update_fields=["poster_images", "banner_images"])
            updated += 1

    # print(f"Movies updated: {updated}")


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0017_movie_banner_images_movie_poster_images'),
    ]

    operations = [
        migrations.RunPython(forward),
    ]
