# Generated by Django 5.1.4 on 2025-08-31 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0018_auto_20250831_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='banner_poster',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='image_poster',
        ),
    ]
