# Generated by Django 5.1.4 on 2025-09-21 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0019_remove_movie_banner_poster_remove_movie_image_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
