# Generated by Django 5.1.4 on 2025-11-06 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0020_movie_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='trailers',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
