# Generated by Django 5.1.4 on 2025-11-08 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0021_alter_movie_trailers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='description',
            new_name='overview',
        ),
    ]
