# Generated by Django 5.1.4 on 2025-11-12 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0023_alter_movie_imdb_id_alter_movie_vote_average'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='released',
        ),
    ]
