# Generated by Django 5.1.4 on 2026-01-16 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0024_remove_movie_released'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['-id'], 'verbose_name': 'Movie', 'verbose_name_plural': 'Movies'},
        ),
    ]
