# Generated by Django 5.1.4 on 2026-02-04 18:31

from django.db import migrations
from django.contrib.postgres.operations import UnaccentExtension


class Migration(migrations.Migration):
    # This will allow django and postgres to perform query with the unaccent extension
    # and to ue the lookup '__unaccent'

    dependencies = [
    ]

    operations = [
        UnaccentExtension(),
    ]
