# Generated by Django 5.1.4 on 2025-01-06 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='profile_pictures/default_user_photo_p.png', upload_to='profile_pictures/'),
        ),
    ]
