# Generated by Django 5.1.4 on 2025-01-07 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='profile_pictures/default_user_pic.png', upload_to='profile_pictures/'),
        ),
    ]
