# Generated by Django 5.1.4 on 2025-04-20 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='background_picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/background_pictures/'),
        ),
    ]
