# Generated by Django 5.1.4 on 2025-04-24 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_profile_background_picture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['id'], 'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
        migrations.AlterModelTable(
            name='profile',
            table='profile',
        ),
    ]
