# Generated by Django 5.1.4 on 2025-09-23 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_profile_options_alter_profile_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='watchlist_private',
            field=models.BooleanField(default=True, help_text='Make watchlist private (only you can see it)'),
        ),
    ]
