# Generated by Django 5.1.4 on 2025-11-06 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_profile_watchlist_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='watchlist_private',
            field=models.BooleanField(default=True, help_text='Toggle watchlist between private and public'),
        ),
    ]
