# Generated by Django 5.1.4 on 2026-05-21 21:33

import django.db.migrations.operations.special
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# comment.migrations.0008_populate_media_field

class Migration(migrations.Migration):

    replaces = [('comment', '0001_initial'), ('comment', '0002_alter_comment_options_alter_comment_user_and_more'), ('comment', '0003_comment_updated_at'), ('comment', '0004_comment_is_active_comment_slug_and_more'), ('comment', '0005_comment_movie_comment_serie'), ('comment', '0006_remove_comment_content_type_remove_comment_object_id_and_more'), ('comment', '0007_comment_media_like'), ('comment', '0008_populate_media_field'), ('comment', '0009_remove_comment_only_one_content_type_per_comment_and_more'), ('comment', '0010_alter_like_comment_alter_like_user'), ('comment', '0011_alter_comment_user')]

    initial = True

    dependencies = [
        # ('media_library', '0002_migrate_movie_serie_to_media'),
        ('media_library', '0001_squashed_0002_migrate_movie_serie_to_media'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                # ('content_type', models.CharField(choices=[('movie', 'Movie'), ('serie', 'Serie')], max_length=25)),
                # ('object_id', models.PositiveIntegerField()),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.SET_NULL, null=True, related_name='comments', to=settings.AUTH_USER_MODEL)),
                # added the media field here directly
                # ('media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='media_library.media')),
                ('media', models.ForeignKey(blank=False, null=False, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='media_library.media')),
            ],
            options={
                'ordering': ['-created_at'],
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
        migrations.AlterModelTable(
            name='comment',
            table='comment',
        ),
        migrations.AddField(
            model_name='comment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        # migrations.RunPython(
        #     code=django.db.migrations.operations.special.RunPython.noop,
        #     reverse_code=django.db.migrations.operations.special.RunPython.noop,
        # ),
        # migrations.RunPython(
        #     code=django.db.migrations.operations.special.RunPython.noop,
        #     reverse_code=django.db.migrations.operations.special.RunPython.noop,
        # ),
        # migrations.RemoveField(
        #     model_name='comment',
        #     name='content_type',
        # ),
        # migrations.RemoveField(
        #     model_name='comment',
        #     name='object_id',
        # ),
        # migrations.RunPython(
        #     code=django.db.migrations.operations.special.RunPython.noop,
        #     reverse_code=django.db.migrations.operations.special.RunPython.noop,
        # ),
        # migrations.AddField(
        #     model_name='comment',
        #     name='media',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='media_library.media'),
        # ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='comment.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'like',
                'verbose_name_plural': 'likes',
                'db_table': 'comment_like',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'comment')},
            },
        ),
        # migrations.RunPython(
        #     code=comment.migrations.0008_populate_media_field.forwards,
        #     reverse_code=comment.migrations.0008_populate_media_field.backwards,
        # ),
        migrations.RunPython(
            migrations.RunPython.noop,
            migrations.RunPython.noop,
        ),
        # migrations.AlterField(
        #     model_name='comment',
        #     name='media',
        #     field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='media_library.media'),
        # ),
        # migrations.AlterField(
        #     model_name='like',
        #     name='comment',
        #     field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='comment.comment'),
        # ),
        # migrations.AlterField(
        #     model_name='like',
        #     name='user',
        #     field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_likes', to=settings.AUTH_USER_MODEL),
        # ),
        # migrations.AlterField(
        #     model_name='comment',
        #     name='user',
        #     field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to=settings.AUTH_USER_MODEL),
        # ),
    ]