# Generated by Django 5.1.4 on 2025-11-24 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0004_comment_is_active_comment_slug_and_more'),
        ('movie', '0024_remove_movie_released'),
        ('serie', '0026_alter_serie_imdb_id_alter_serie_vote_average'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='movie.movie'),
        ),
        migrations.AddField(
            model_name='comment',
            name='serie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='serie.serie'),
        ),
    ]
