# Generated by Django 5.1.4 on 2025-11-24 11:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0005_comment_movie_comment_serie'),
        ('movie', '0024_remove_movie_released'),
        ('serie', '0026_alter_serie_imdb_id_alter_serie_vote_average'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='object_id',
        ),
        migrations.AddConstraint(
            model_name='comment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('movie__isnull', False), ('serie__isnull', True)), models.Q(('movie__isnull', True), ('serie__isnull', False)), _connector='OR'), name='only_one_content_type_per_comment'),
        ),
    ]
