# Generated by Django 5.1.4 on 2026-05-05 13:05

from django.db import migrations, transaction

CHUNK_SIZE = 500

def forwards(apps, schema_editor):

    comment_model = apps.get_model("comment", "Comment")
    transfer_map = apps.get_model("media_library", "MediaTransferMap")

    movie_map = dict(
        transfer_map.objects.filter(media_type="movie").values_list(
            "old_pk", "new_media_pk"
        )
    )
    serie_map = dict(
        transfer_map.objects.filter(media_type="serie").values_list(
            "old_pk", "new_media_pk"
        )
    )

    skipped = 0

    with transaction.atomic():
        for comment in comment_model.objects.iterator(chunk_size=CHUNK_SIZE):
            new_media_pk = None  # reset each loop

            if comment.movie_id:
                new_media_pk = movie_map.get(comment.movie_id)
            elif comment.serie_id:
                new_media_pk = serie_map.get(comment.serie_id)

            if not new_media_pk:
                print(f"WARNING: no media mapping for comment pk={comment.pk}")
                skipped += 1
                continue # Skip, no saving.

            comment.media_id = new_media_pk
            comment.save()

    print(f"Comments migrated. Skipped: {skipped}")

def backwards(apps, schema_editor):
    comment_model = apps.get_model("comment", "Comment")
    comment_model.objects.all().update(media=None)


class Migration(migrations.Migration):

    dependencies = [
        ("media_library", "0002_migrate_movie_serie_to_media"),
        ('comment', '0007_comment_media_like'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
