# Generated by Django 5.1.4 on 2026-05-06 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0008_populate_media_field'),
        ('media_library', '0002_migrate_movie_serie_to_media'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='comment',
            name='only_one_content_type_per_comment',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='serie',
        ),
        migrations.AlterField(
            model_name='comment',
            name='media',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='media_library.media'),
        ),
    ]
