# Generated by Django 5.1.4 on 2026-05-21 22:04

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# media_library.migrations.0002_migrate_movie_serie_to_media

class Migration(migrations.Migration):

    replaces = [('media_library', '0001_initial'), ('media_library', '0002_migrate_movie_serie_to_media')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('media_type', models.CharField(choices=[('movie', 'Movie'), ('serie', 'Serie')], db_index=True, max_length=10)),
                ('original_title', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(max_length=255)),
                ('overview', models.TextField(blank=True, null=True)),
                ('tagline', models.TextField(blank=True, null=True)),
                ('genre', models.JSONField(blank=True, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('origin_country', models.JSONField(blank=True, null=True)),
                ('original_language', models.CharField(blank=True, max_length=50, null=True)),
                ('spoken_languages', models.JSONField(blank=True, null=True)),
                ('production', models.JSONField(blank=True, null=True)),
                ('vote_average', models.FloatField(blank=True, help_text='Select a value between 0 and 10.', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('vote_count', models.IntegerField(blank=True, null=True)),
                ('popularity', models.FloatField(blank=True, null=True)),
                ('banner_images', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None)),
                ('poster_images', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('adult', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Media',
                'verbose_name_plural': 'Media',
                'db_table': 'media',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('media_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='media_library.media')),
                ('director', models.JSONField(blank=True, null=True)),
                ('writer', models.JSONField(blank=True, null=True)),
                ('casting', models.JSONField(blank=True, null=True)),
                ('length', models.IntegerField(blank=True, null=True)),
                ('trailers', models.JSONField(blank=True, null=True)),
                ('budget', models.IntegerField(blank=True, null=True)),
                ('revenue', models.BigIntegerField(blank=True, null=True)),
                ('tmdb_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('imdb_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Movie',
                'verbose_name_plural': 'Movies',
                'db_table': 'media_lirary_movie',
                'ordering': ['-id'],
            },
            bases=('media_library.media',),
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('media_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='media_library.media')),
                ('first_air_date', models.DateField(blank=True, null=True)),
                ('last_air_date', models.DateField(blank=True, null=True)),
                ('created_by', models.JSONField(blank=True, null=True)),
                ('tmdb_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('imdb_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Serie',
                'verbose_name_plural': 'Series',
                'db_table': 'media_lirary_serie',
                'ordering': ['-id'],
            },
            bases=('media_library.media',),
        ),
        # migrations.CreateModel(
        #     name='MediaTransferMap',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('media_type', models.CharField(choices=[('movie', 'Movie'), ('serie', 'Serie')], max_length=10)),
        #         ('old_pk', models.IntegerField()),
        #         ('new_media_pk', models.IntegerField()),
        #     ],
        #     options={
        #         'db_table': 'media_library_transfer_map',
        #         'unique_together': {('media_type', 'old_pk')},
        #     },
        # ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('season_number', models.IntegerField()),
                ('overview', models.TextField(blank=True, null=True)),
                ('producer', models.JSONField(blank=True, max_length=255, null=True)),
                ('casting', models.JSONField(blank=True, null=True)),
                ('poster_images', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None)),
                ('trailers', models.JSONField(blank=True, null=True)),
                ('tmdb_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='media_library.serie')),
            ],
            options={
                'verbose_name': 'Season',
                'verbose_name_plural': 'Seasons',
                'db_table': 'media_lirary_season',
                'ordering': ['serie', 'season_number'],
                'unique_together': {('serie', 'season_number')},
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('episode_number', models.IntegerField()),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('overview', models.TextField(blank=True, null=True)),
                ('length', models.IntegerField(blank=True, help_text='Average episode length in minutes', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('release_date', models.DateField(blank=True, null=True)),
                ('guest_star', models.JSONField(blank=True, null=True)),
                ('director', models.JSONField(blank=True, null=True)),
                ('writer', models.JSONField(blank=True, null=True)),
                ('banner_images', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None)),
                ('tmdb_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='media_library.season')),
            ],
            options={
                'verbose_name': 'Episode',
                'verbose_name_plural': 'Episodes',
                'db_table': 'media_lirary_episode',
                'ordering': ['season', 'episode_number'],
                'unique_together': {('season', 'episode_number')},
            },
        ),
        # migrations.RunPython(
        #     code=media_library.migrations.0002_migrate_movie_serie_to_media.forwards,
        #     reverse_code=media_library.migrations.0002_migrate_movie_serie_to_media.backwards,
        # ),
        migrations.RunPython(
            migrations.RunPython.noop,
            migrations.RunPython.noop,
        ),
    ]
