# Generated by Django 5.1.4 on 2026-05-25 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0001_squashed_0002_migrate_movie_serie_to_media'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='episode',
            table='episode',
        ),
        migrations.AlterModelTable(
            name='movie',
            table='movie',
        ),
        migrations.AlterModelTable(
            name='season',
            table='season',
        ),
        migrations.AlterModelTable(
            name='serie',
            table='serie',
        ),
    ]
